### ISSUE TITLE
Search bar support

### ISSUE THREAD

**Issue by kuskus-39** [Konosprod/JishoSearchPluginFirefox#1]
Hi! Could you please add your add-on as a search engine? I'd love to use Jisho straight from the search bar like you can do with Google, Duckduckgo, Wikipedia etc. `@[Jj]isho` would do well as the keyword. Have a great day!
(If you're busy, I could also do this myself and make a pull request, although it might not be quick)

**Comment by Konosprod** [comment]
You can already do it if I remember correctly. When you are on the Jisho page, you click on the URL bar, it will show a list of your bookmarks or history & stuff. At the bottom of this list, you'll see the jisho icon with a small "+" on it. Click on it to add Jisho as one of your search engine. Go then in your preferences => Search => Add your keyword to Jisho !

![add_search](https://user-images.githubusercontent.com/1846899/125740447-8a89b993-9e42-442b-b9c0-e0e947050af8.png)
![config](https://user-images.githubusercontent.com/1846899/125740471-0a3584dd-3b2c-4eb1-93e8-a27a564d440c.png)

**Comment by kuskus-39** [comment]
Thank you for the quick response! It works. Have a good day uwu
